ballerina-guides/gcp-microservices-demo

cart/Dependencies.toml
cart/cart_service.bal
cart/datastores.bal

Add Redis cache in cart service
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

Add redis cache in cart service

---

ads/Dependencies.toml
ads/service.bal
cart/Dependencies.toml
cart/cart_service.bal
checkout/Dependencies.toml
checkout/checkout_service.bal
currency/Dependencies.toml
currency/currency_service.bal
email/Dependencies.toml
email/email_service.bal
frontend/Dependencies.toml
frontend/rpc.bal
frontend/service.bal
payment/Dependencies.toml
payment/payment_service.bal
productcatalog/Dependencies.toml
productcatalog/catalog_service.bal
project.code-workspace
recommendation/Dependencies.toml
recommendation/recommendation_service.bal
shipping/Dependencies.toml
shipping/shipping_service.bal

Include changes to render the design view

Project design demo

---

.github/workflows/daily-build.yml
.github/workflows/pull-request.yml

$Subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Fix workflows to run on latest ballerina version

---

ads/service.bal
ads/store.bal
ads/tests/test.bal

Fix ads service

---

ui/package-lock.json
ui/src/pages/Cart.js

$Subject.
To fix a bug where text fields are not modifiable. 
Resolves #19
> Link to the PR for changes to the training content …

Change value to defaultValue in forms

---

frontend/rpc.bal
frontend/service.bal
frontend/types.bal
frontend/utils.bal

Update syntax in frontend code

---

ads/service.bal
cart/cart_service.bal
cart/datastores.bal
checkout/checkout_service.bal
currency/currency_service.bal
payment/card-validator.bal
payment/payment_service.bal
productcatalog/catalog_service.bal
recommendation/recommendation_service.bal

Improve the code in grpc services

---

ads/ads_service.bal
cart/cart_service.bal
cart/datastores.bal
checkout/checkout_service.bal
currency/currency_service.bal
email/email_service.bal
payment/payment_service.bal
productcatalog/catalog_service.bal
recommendation/recommendation_service.bal
shipping/shipping_service.bal

We need to return `Empty` here explicitly as `Empty` is a record defined the proto file

Fix issue in return value and add lables

---

frontend/rpc.bal
frontend/service.bal
frontend/types.bal
frontend/utils.bal

Refactor code in Frontend service

---

ads/ads_service.bal
cart/cart_service.bal
checkout/checkout_service.bal
currency/currency_service.bal
email/email_service.bal
frontend/types.bal
payment/payment_service.bal
productcatalog/catalog_service.bal
recommendation/recommendation_service.bal
shipping/shipping_service.bal

Remove explicit isolation keyword

---

checkout/tests/test.bal
recommendation/tests/Config.toml
recommendation/tests/test.bal
ui/src/components/products/Order.js

Fix minor issues in tests and ui

---

frontend/service.bal
ui/package.json
ui/public/index.html
ui/public/manifest.json

$subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Add website name

---

ads/Ballerina.toml
cart/Ballerina.toml
checkout/Ballerina.toml
currency/Ballerina.toml
email/Ballerina.toml
frontend/Ballerina.toml
payment/Ballerina.toml
productcatalog/Ballerina.toml
recommendation/Ballerina.toml
shipping/Ballerina.toml

$subject
Fixes https://github.com/ballerina-guides/gcp-microservices-demo/issues/35
> Link to the PR for changes to the training …

Update distribution version

---

ads/ads_service.bal
cart/cart_service.bal
checkout/checkout_service.bal
currency/currency_service.bal
email/email_service.bal
frontend/service.bal
payment/payment_service.bal
productcatalog/catalog_service.bal
recommendation/recommendation_service.bal
shipping/shipping_service.bal

Remove manual span in services

---

README.md

$subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Update readme for port forwading

---

README.md
ads/ads_service.bal
checkout/checkout_service.bal
email/email_service.bal
payment/payment_service.bal
recommendation/recommendation_service.bal
shipping/shipping_service.bal

Add uniform logs

---

project.code-workspace

Update workspace file due to latest name changes

---

cartservice/cart_service.bal
cartservice/datastores.bal
checkoutservice/checkout_service.bal
currencyservice/currency_service.bal
emailservice/email_service.bal
paymentservice/payment_service.bal
productcatalogservice/catalog_service.bal
project.code-workspace
recommendationservice/recommendation_service.bal
shippingservice/shipping_service.bal

Add minor code improvements and log message updates

---

frontend/service.bal
frontend/utils.bal

Add minor source code improvements

---

README.md

Remove invalid step from README.md

---

README.md
docker-compose.yml

> Fixes https://github.com/ballerina-guides/gcp-microservices-demo/issues/81
> Link to the PR for changes to the training content …

Update config title to align with the implementation

---

README.md
build-all-k8s.sh

> Fixes https://github.com/ballerina-guides/gcp-microservices-demo/issues/84
> Link to the PR for changes to the training content …

Refactor K8s deployment steps and build script

---

.github/workflows/daily-build.yml
.github/workflows/pull-request.yml

> Include ballerina-platform Action

Include ballerina-platform Action
